### ISSUE TITLE
Kitty Items does not work - Initialize Account

### ISSUE THREAD

**Issue by kev2513** [onflow/kitty-items#102]
Kitty Items demo page does not work (http://kitty-items-flow-testnet.herokuapp.com)

Just create a new account with Blocto and click "Initialize Account".

![image](https://user-images.githubusercontent.com/38647302/122442191-96fede80-cf9e-11eb-9a37-3b65de575ee9.png)

Yesterday the service timed out after clicking "Initialize Account" and today I got rejected. I used Chrome on Mac and Android.

**Comment by 10thfloor** [comment]
Thanks for creating an issue.
