### ISSUE TITLE
Buy button throws an error

### ISSUE THREAD

**Issue by nosovk** [onflow/kitty-items#106]
**Describe the bug**
When I try to buy an item  via button "Buy" it fails with some error in console.

**To Reproduce**
Login to shop on testnet with Blockto wallet.
Init account.
Mint.
Buy an item at Item Marketplace screen.

**Expected behavior**
Item should be acquired by me.

**Screenshots/Logs/Output**
![image](https://user-images.githubusercontent.com/1398808/123454886-b5da2200-d5e9-11eb-8900-20ed5cec4e47.png)

**Environment (Optional - Version, OS, Browser, etc.)**
Chrome, Version 93.0.4542.2 (Official Build) dev (64-bit)
Manjaro Linux

Error in console:

```
tx.js:5 TX[64ec98ec8f325688c9619a733e44e67bb6523aa057f396d19e52a42387efd942]: https://flow-view-source.com/testnet/tx/64ec98ec8f325688c9619a733e44e67bb6523aa057f396d19e52a42387efd942 [Error Code: 1101] cadence runtime error Execution failed:
error: unexpectedly found nil while forcing an Optional value
  --> 64ec98ec8f325688c9619a733e44e67bb6523aa057f396d19e52a42387efd942:17:74
   |
17 |           let price = self.marketCollection.borrowSaleItem(itemID: itemID)!.price
   |                                                                           ^
   ```

**Comment by 10thfloor** [comment]
@nosovk Are you running your own version, or is this on the deployed version?

**Comment by nosovk** [comment]
it was on deployed version
