### ISSUE TITLE
npm run start:testnet failed

### ISSUE THREAD

**Issue by vchhajed** [onflow/kitty-items#108]
> kitty-items@1.0.0 start:testnet /home/vaibhav/kitty-items
> ./scripts/run-testnet.sh

sh: 1: ./scripts/run-testnet.sh: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! kitty-items@1.0.0 start:testnet: `./scripts/run-testnet.sh`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the kitty-items@1.0.0 start:testnet script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vaibhav/.npm/_logs/2021-06-28T21_59_33_962Z-debug.log

**Comment by marcomarchesi** [comment]
you may add  execute permissions with `chmod +x run-testnet.sh` and try again.

**Comment by vchhajed** [comment]
Worked
