### ISSUE TITLE
having issues deploying on heroku

### ISSUE THREAD

**Issue by Meharab** [onflow/kitty-items#111]
**having issues deploying on heroku**
it didn't respond to test net 

**OS : windows 10**

**Screenshots/Logs/Output**
![Screenshot 2021-07-02 222755](https://user-images.githubusercontent.com/33731973/124311879-3bcd0e80-db90-11eb-8054-377d0268ef95.jpg)
![Screenshot 2021-07-02 222846](https://user-images.githubusercontent.com/33731973/124311888-412a5900-db90-11eb-80fe-2fe32f1ea934.jpg)

**Comment by 10thfloor** [comment]
The Heroku UI is broken. Once you've innput the values, you'll need to click into every input and hit the delete key. You have to do this for _every_ input, even one's that have been pre-filled by the config.

**Comment by Suprove-99** [comment]
I am having the same issue while deploying on Heroku.. Did you solve it?

**Comment by 10thfloor** [comment]
Closing because we're going to remove the Heroku deployment.
