### ISSUE TITLE
Mint button not working

### ISSUE THREAD

**Issue by nosovk** [onflow/kitty-items#113]
Mint button in demo broken

Login using blockto, init, mint

Expected behavior:
anything except silent error :)

Screenshots:
![image](https://user-images.githubusercontent.com/1398808/124349444-b0876380-dbf7-11eb-884a-3225dc55d6af.png)

Chrome 91, Linux

**Comment by 10thfloor** [comment]
@nosovk Thanks for the issue. Will look into this today.

**Comment by MAkcanca** [comment]
Did this get resolved?

**Comment by nosovk** [comment]
nope

**Comment by 10thfloor** [comment]
This should be resolved now.
