### ISSUE TITLE
Connection denied from localhost

### ISSUE THREAD

**Issue by fontanamichele** [onflow/kitty-items#118]
**Describe the bug**
Hello everyone, 
I have this issues when I try to deploy the project on emulator, I'm running the node server on a vps 
I've setup the project following the LOCAL_DEV.md file, everythings seems to work fine, when I run the command  npm run start:dev it doesn't display any error, but when I reach my server on chrome it display this:
PORT 3001 display kitty logo with sign in and signup button, but when i click on it I get a grey screen and the message "connection denied from localhost"
PORT 3000 print "not found"
PORT 8701 redirect to /accounts and display account info
PORT 5432 page not working "the page is not sanding any data"
PORT 8080 print "gRPC requires HTTP/2"
this is what the console display after I run the command: 
`
> kitty-items@1.0.0 start:dev
> ./scripts/run-local.sh "npm" "run" "start:dev"
lerna notice cli v4.0.0
lerna info Executing command in 3 packages: "npm run dev"
kitty-items-api: > kitty-items-api@0.0.1 dev
kitty-items-api: > tsnd src/index.ts --respawn --dev
fcl-dev-wallet: > fcl-dev-wallet@0.1.0 dev
fcl-dev-wallet: > next dev --port 8701
kitty-items-web: > kitty-items-web@0.1.0 dev
kitty-items-web: > export PORT=3001 && react-scripts start
kitty-items-api: [INFO] Invalid Date ts-node-dev ver. 1.1.7 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
fcl-dev-wallet: Loaded env from /root/fcl-dev-wallet/.env.local
fcl-dev-wallet: (node:64624) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /root/fcl-dev-wallet/node_modules/postcss/package.json.
fcl-dev-wallet: Update this package.json to use a subpath pattern like "./*".
fcl-dev-wallet: (Use `node --trace-deprecation ...` to show where the warning was created)
fcl-dev-wallet: ready - started server on 0.0.0.0:8701, url: http://localhost:8701
kitty-items-web: ℹ ｢wds｣: Project is running at http://0.0.0.0:3001/
kitty-items-web: ℹ ｢wds｣: webpack output is served from
kitty-items-web: ℹ ｢wds｣: Content not from webpack is served from /root/web/public
kitty-items-web: ℹ ｢wds｣: 404s will fallback to /
kitty-items-web: Starting the development server...
fcl-dev-wallet: event - compiled successfully
kitty-items-api: Starting Flow event worker ....
kitty-items-api: fetching latest block height
kitty-items-api: Starting API server ....
kitty-items-api: Listening on port 3000!
kitty-items-api: latestBlockHeight = 20
kitty-items-api: fromBlock=20 toBlock=20 latestBlock=20
kitty-items-api: fromBlock=20 toBlock=20 latestBlock=20
kitty-items-web: Compiled with warnings.
kitty-items-web: ./src/pages/root.page.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/pages/not-found.page.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/pages/account/index.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/base.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/auth-cluster.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/init-cluster.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/balance-cluster.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/market-items-cluster.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/account-items-cluster.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/parts/market-item-cluster.comp.js
kitty-items-web:   Line 1:17:  'Component' is defined but never used  no-unused-vars
kitty-items-web: ./src/hooks/use-market-item.hook.js
kitty-items-web:   Line 45:6:  React Hook useEffect has missing dependencies: 'key' and 'setItem'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
kitty-items-web: Search for the keywords to learn more about each warning.
kitty-items-web: To ignore, add // eslint-disable-next-line to the line before.
`

I don't even know if this is a problem with the emulator, the flow api, my server or postgress (the last one in fact I'm using it for the first time)
I hope someone can help me as I have been stuck on this step for a long time now, if some information is missing to identify the problem, please write it so I am attaching it. 
Thanks in advice

**Comment by 10thfloor** [comment]
@fontanamichele Hey sorry to hear that. The old local instructions are getting an upgrade. 
Take a look at this branch for the latest. This will get merged very soon.

**Comment by fontanamichele** [comment]
First of all thank you for your time,
in your opinion, therefore, until the documentation is updated, I will not be able to test my contracts? Is there another way to deploy this dapp in "edit" mode?
I have read that releasing the contracts on the testnet implies the impossibility of modifying them independently.

**Comment by Ectsang** [comment]
anyone have any updates on this?

**Comment by 10thfloor** [comment]
This should no longer be an issue.
