### ISSUE TITLE
Heroku deployment button on README just hangs

### ISSUE THREAD

**Issue by thatguyintech** [onflow/kitty-items#125]
**Describe the bug**
In the README, the heroku deployment button loads but hangs, even after authenticating via login. This prevents me from being able to try out what it's like to deploy the app myself and customize deployment configs. I've also tried copying the repo and deploying to Heroku via my own account but I run into a lot of configuration issues with env vars not being recognized by Heroku.

**To Reproduce**

Go to https://github.com/onflow/kitty-items#optional-heroku-deployment, click on the Deploy to Heroku button
<img width="593" alt="Screen Shot 2021-07-30 at 8 59 29 AM" src="https://user-images.githubusercontent.com/3393523/127679974-1d00f6e6-0a04-404b-b7da-3b8f531058db.png">

**Screenshots/Logs/Output**
If applicable, add screenshots or logs to help explain your problem.

**Environment (Optional - Version, OS, Browser, etc.)**
I'm on MacOS Big Sur V 11.3.1
Brave Browser v1.27.109

**Additional context (Optional - Anything else about the bug)**

**Comment by 10thfloor** [comment]
I could not reproduce. I was able to deploy using the button. This could be an issue with Heroku itself.
Specific deployment configuration instructions are not in scope for this project. The Heroku deployment is offered for example only.

**Comment by thatguyintech** [comment]
gotcha, thanks!
