### ISSUE TITLE
 Cannot run under windows10

### ISSUE THREAD

**Issue by msyzzm** [onflow/kitty-items#128]
**Describe the bug**
If i start run with "npm run start:testnet", it will excute run-testnet.sh. In this file, export command cannot work in windows10.

**To Reproduce**
run "npm run start:testnet".

**Expected behavior**
Let it run correctly, it will help a lot.

**Environment (Optional - Version, OS, Browser, etc.)**
Windows 10, GitBash

**Comment by magusfabius** [comment]
so docker a go go go g o'ogogogogoogogo! LoL

**Comment by msyzzm** [comment]
> so docker a go go go g o'ogogogogoogogo! LoL

Now, i run it in a ubuntu system, and share the folder through SMB, edit with windows.

**Comment by MrDSGC** [comment]
Issue should be resolved here #268
