### ISSUE TITLE
BaseEventHandler often encounters errors

### ISSUE THREAD

**Issue by msyzzm** [onflow/kitty-items#129]
**Describe the bug**
BaseEventHandler often encounters errors.

> kitty-items-api: Error retrieving events for block range fromBlock=41436378 toBlock=41436384 Error: start height 41436378 is greater than the last sealed block height 41436375
kitty-items-api:     at Object.onEnd (/root/smbshare/kitty-items/api/node_modules/@onflow/sdk/src/send/unary.js:18:18)
kitty-items-api:     at /root/smbshare/kitty-items/api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24140
kitty-items-api:     at /root/smbshare/kitty-items/api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11457
kitty-items-api:     at Array.forEach (<anonymous>)
kitty-items-api:     at e.rawOnError (/root/smbshare/kitty-items/api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11419)
kitty-items-api:     at e.onTransportHeaders (/root/smbshare/kitty-items/api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:8996)
kitty-items-api:     at NodeHttp.responseCallback (/root/smbshare/kitty-items/api/node_modules/@improbable-eng/grpc-web-node-http-transport/src/index.ts:36:18)
kitty-items-api:     at Object.onceWrapper (node:events:514:26)
kitty-items-api:     at ClientRequest.emit (node:events:394:28)
kitty-items-api:     at HTTPParser.parserOnIncomingClient (node:_http_client:621:27)

The cause of the error may be the wrong value returned by getLatestBlockHeight.

**To Reproduce**
Run "npm run start:testnet", Will happen in a while.

**Environment (Optional - Version, OS, Browser, etc.)**
Ubuntu 20.04

**Comment by 10thfloor** [comment]
Weird, I think this can be fixed by resetting the block cursor in your local db. 
The easiest way to reset your local block-cursor, is to remove all rows from the table, and restart the app, to repopulate with an out of date cursor. 

The errors will go away once the block height exceeds the start height (so, as more blocks get processed).

If none of these solutions work, we can look at debugging this, or maybe adding code that does the reset automatically.

**Comment by msyzzm** [comment]
> Weird, I think this can be fixed by resetting the block cursor in your local db.
> The easiest way to reset your local block-cursor, is to remove all rows from the table, and restart the app, to repopulate with an out of date cursor.
> 
> The errors will go away once the block height exceeds the start height (so, as more blocks get processed).
> 
> If none of these solutions work, we can look at debugging this, or maybe adding code that does the reset automatically.

I think the method（getLatestBlockHeight ）can ensure that such errors will not occur, becouse the "toBlock" will never greater than LatestBlockHeight.
Did I understand something wrong?

**Comment by 10thfloor** [comment]
That is basically correct. There is some code in this PR that addresses the issue. 
https://github.com/onflow/kitty-items/pull/132
