### ISSUE TITLE
npm run start:testnet getting error

### ISSUE THREAD

**Issue by dennygajera** [onflow/kitty-items#137]
**Describe the bug**
Define and run multi-container applications with Docker

**To Reproduce**
After installing all packages and setup when trying to run on testnet.

**Additional context **
When config the "docker-compose.yml" file, getting this error.

WARNING: The CHAIN_ENV variable is not set. Defaulting to a blank string.
WARNING: The ACCESS_API_WEB variable is not set. Defaulting to a blank string.
WARNING: The WALLET_DISCOVERY variable is not set. Defaulting to a blank string.
WARNING: The FUNGIBLE_TOKEN_ADDRESS variable is not set. Defaulting to a blank string.
WARNING: The NON_FUNGIBLE_TOKEN_ADDRESS variable is not set. Defaulting to a blank string.
WARNING: The FUSD_ADDRESS variable is not set. Defaulting to a blank string.
WARNING: The API_URL variable is not set. Defaulting to a blank string.
WARNING: The ACCESS_API_BACKEND variable is not set. Defaulting to a blank string.
WARNING: The DB_URL variable is not set. Defaulting to a blank string.
WARNING: The FLOW_PUBLIC_KEY variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.api: 'profiles'
Unsupported config option for services.db: 'profiles'
Unsupported config option for services.dev-wallet: 'profiles'
Unsupported config option for services.emulator: 'profiles'
Unsupported config option for services.web: 'profiles'

**Comment by 10thfloor** [comment]
Can you provide more details about your issue?
- Operating System
- Docker version

**Comment by 10thfloor** [comment]
Closing because stale.
