### ISSUE TITLE
NFTStoreFront is different from one deployed on Testnet

### ISSUE THREAD

**Issue by MaxStalker** [onflow/kitty-items#139]
`NFTStoreFront` contract used in KittyItems - https://github.com/onflow/kitty-items/blob/master/cadence/contracts/NFTStorefront.cdc -  is different from the one currently deployed on Testnet at `0x94b06cfca1d8a476`.

While it would work if developer redeploy the contract and use new address, it breaks the purpose of using `NFTStoreFront` contract as unified way of trading tokens.

**Comment by 10thfloor** [comment]
@rheaplex Is this still a thing? Where can I find the testnet version?

**Comment by rheaplex** [comment]
I haven't been involved in KittyItems deployment for a while. Maybe ask @psiemens ?

**Comment by psiemens** [comment]
This is resolved now. Thanks Max!
