### ISSUE TITLE
Unable to initialize account

### ISSUE THREAD

**Issue by jamesthesken** [onflow/kitty-items#141]
**Describe the bug**
After selecting "Initialize Account" I receive the following error in the console:
```
[Error Code: 1101] cadence runtime error Execution failed:
error: failed to save object: path /storage/fusdVault in account 0x2568a04f77bde8b1 already stores an object
  --> ccd4287488c62f03d531d6181e8f3ef84223f8caee883322a183275ad304fad2:35:10
   |
35 |           acct.save(<-FUSD.createEmptyVault(), to: /storage/fusdVault)
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**

- Sign in to Blocto
- Click on "Initialize Account"
- Select "Approve" when prompted for Blocto signature

**Expected behavior**
Account initialization and ability to request FUSD on the testnet - I think :)

**Screenshots/Logs/Output**

**Environment (Optional - Version, OS, Browser, etc.)**
OS: macOS Catalina 10.15.7
Browser: Safari 14.1.2 and Firefox 89.0 

**Additional context (Optional - Anything else about the bug)**
Thank you for any help or guidance!

**Comment by ic3guy** [comment]
I am seeing this as well.

**Comment by 10thfloor** [comment]
@ic3guy @jamesthesken This is fixed now. The issue was the app was pointing to the incorrect address for the FUSD contract.
