### ISSUE TITLE
Can't deploy customised contracts on testnet

### ISSUE THREAD

**Issue by W3-MajorArif** [onflow/kitty-items#144]
**Describe the bug**
I've cloned your project, modified some places to support metadata in NFT. I've deployed it in local emulator and it's working well. Then I've tried to deploy the contracts in testnet following your guideline and facing issues with parameter mismatch. Not sure what wrong I'm doing here

**To Reproduce**
I'm attaching here all my cadence files. With those I tried https://github.com/onflow/kitty-items#testnet-development process and found error like 

**Screenshots/Logs/Output**

❌ Error deploying KittyItems: ([Error Code: 1101] cadence runtime error Execution failed:
error: cannot deploy invalid contract
 --> 36042898da8d8c40e1220c1139f95f3a1a06c240bcd7636cdfa5e82cdab65968:4:3
  |
4 |                     signer.contracts.add(name: name, code: code.decodeHex() )
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: event `KittyItems.Deposit` does not conform to event type requirement `NonFungibleToken.Deposit`
  --> f64c160728f9f593.KittyItems:12:14
   |
12 |     pub event Deposit(id: UInt64, to: Address?, metadata: {String : String})
   |               ^

error: resource `KittyItems.Collection` does not conform to resource type requirement `NonFungibleToken.Collection`
  --> f64c160728f9f593.KittyItems:65:17
   |
65 |     pub resource Collection: KittyItemsCollectionPublic, NonFungibleToken.Provider, NonFungibleToken.Receiver, NonFungibleToken.CollectionPublic {
   |                  ^
  ... 
   |
94 |         pub fun deposit(token: @NonFungibleToken.NFT, metadata: {String : String}) {
   |                 ------- mismatch here

error: resource `KittyItems.Collection` does not conform to resource interface `NonFungibleToken.Receiver`
  --> f64c160728f9f593.KittyItems:65:17
   |
65 |     pub resource Collection: KittyItemsCollectionPublic, NonFungibleToken.Provider, NonFungibleToken.Receiver, NonFungibleToken.CollectionPublic {
   |                  ^
  ... 
   |
94 |         pub fun deposit(token: @NonFungibleToken.NFT, metadata: {String : String}) {
   |                 ------- mismatch here

error: resource `KittyItems.Collection` does not conform to resource interface `NonFungibleToken.CollectionPublic`
  --> f64c160728f9f593.KittyItems:65:17
   |
65 |     pub resource Collection: KittyItemsCollectionPublic, NonFungibleToken.Provider, NonFungibleToken.Receiver, NonFungibleToken.CollectionPublic {
   |                  ^
  ... 
   |
94 |         pub fun deposit(token: @NonFungibleToken.NFT, metadata: {String : String}) {
   |                 ------- mismatch here

error: incorrect number of arguments
   --> f64c160728f9f593.KittyItems:182:3
    |
182 |                   recipient.deposit(token: <-newNFT, metadata: metadata)
    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1, got 2
)

**Expected behavior**

**Environment (Optional - Version, OS, Browser, etc.)**
I'm using mac-mini, osx-11.5.1, under docker environment

**Additional context (Optional - Anything else about the bug)**
If you could please help me with how to resolve the issue, that will be very appreciated.
Thank you
[contracts.zip](https://github.com/onflow/kitty-items/files/7283449/contracts.zip)

**Comment by 10thfloor** [comment]
I think the first error is the most relevant: `error: cannot deploy invalid contract`
This usually means you have a syntax error somewhere. 
An easy way to validate your contracts is to head over to https://play.onflow.org and paste your contract into the editor. 
You should see error messages that will help you track down your syntax issue.

**Comment by MrDSGC** [comment]
Closing inactive issue. Let us know if you are still experiencing this bug!
