### ISSUE TITLE
deploy testnet issue 

### ISSUE THREAD

**Issue by TracyH1988** [onflow/kitty-items#149]
**Describe what is not documented**
when excute : npm run start:testnet, same as  :  docker-compose --env-file .env.testnet --profile testnet up -d

failed :
![image](https://user-images.githubusercontent.com/13996290/144837366-31daca16-7991-4f2e-b650-bd01eec6bb31.png)

How to fix it or did I miss something? thanks

**Comment by 10thfloor** [comment]
Hi @TracyH1988 
This appears to be an issue with a specific version of Docker Compose. 
You may want to try the suggestions here: 
https://stackoverflow.com/questions/67010408/unable-to-start-docker-container-from-docker-compose-unknown-flag-iidfile

**Comment by 10thfloor** [comment]
Closing because wontfix.
