### ISSUE TITLE
Current heroku deployment is not working

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [onflow/kitty-items#163]
**Describe the bug**
I'm trying to deploy to heroku and from what i see in the [Procfile](https://github.com/onflow/kitty-items/blob/master/Procfile)  there is only 2 processes and both are pointing to the api application through `npm run start` and n`pm run start:worker`, do i need to edit the Procfile to add the web and db apps? I assumed it's preconfigured already ...

**To Reproduce**
- connect the repo to heroku for deployment, it won't work

**Expected behavior**

**Screenshots/Logs/Output**
If applicable, add screenshots or logs to help explain your problem.

**Environment (Optional - Version, OS, Browser, etc.)**

**Additional context (Optional - Anything else about the bug)**

**Comment by psiemens** [comment]
Thanks for reporting this @ahmed-adly-khalil. 

@10thfloor, do you think you could look into this?

**Comment by alxflw** [comment]
@10thfloor looks like we should fix this before initial release. any idea when you might get to this?
