### ISSUE TITLE
upgrade flow-js-testing when flow-js-testing library uses HTTP API call to check emulator status

### ISSUE THREAD

**Issue by kerrywei** [onflow/kitty-items#170]
## Context
There is artificial delayed added in beforeEach and afterEach Jest fixtures in order to avoid tests started before the emulator is fully up & running (for details, see https://github.com/onflow/flow-js-testing/issues/47#issuecomment-1006917613). This workaround is a technical debt and needs to be addressed once a permanent solution from Flow emulator/flow-js-testing library is provided

## Definition of Done
- once issue https://github.com/onflow/flow-js-testing/issues/72 is addressed, upgrade the dependency version to use the latest, remove the artificial delayed introduced in PR https://github.com/onflow/kitty-items/pull/169

**Comment by MrDSGC** [comment]
Closing since issue is resolved
