### ISSUE TITLE
Event worker fails due to unique constraint when inserting into database

### ISSUE THREAD

**Issue by PeterArbaugh** [onflow/kitty-items#176]
Event worker fails due to unique constraint when inserting into database
    - Does not break things but clogs the API logs
    - happens because event worker is stuck on the same block - emulator does not create new blocks until a tx comes in

**Comment by kerrywei** [comment]
update: 
occupied with other tasks, haven't made much progress yet

**Comment by alxflw** [comment]
Hey folks, I'm planning an initial release of KI and taking inventory of our issues. Is this a blocking item for launch or not? It seems it is not breaking things, but wanted to check

**Comment by kerrywei** [comment]
@alxflw this is not blocking anything, but annoying to project contributors as the logging is kinda spammed by this

**Comment by kerrywei** [comment]
blocked by unable to mint items in local dev env per shared in our channel. pending that to be resolved

**Comment by 10thfloor** [comment]
Fixed here: 3fe7d09072

**Comment by kerrywei** [comment]
Thanks for help address this @10thfloor ! do we want to close this now, or anything else needed to close this?
