### ISSUE TITLE
Global progress indicator for transactions

### ISSUE THREAD

**Issue by PeterArbaugh** [onflow/kitty-items#178]
as a user, I should be able to view transaction details, progress, and recent transactions.

Notes:
- Developer should be able to display an optional title for each transaction.
- Decision to show an external link icon on hover so that users understand it is a link to the transaction details

Transitions:
- When a new transaction begins, use a slide animation to slide in from the right
- When we want the element to disappear, we should slide the element off the screen to the right. 
- In both cases, the elements in the nav should slide with the pending element. 

AC:
- When a transaction succeeds, I should see a flash of green on the indicator in the top nav
- When a transaction fails, I should see a flash of red on on the indicator in the top nav
- If there are no longer pending transactions, the element copy would change from “pending” to “complete,” the element would remain the flash color and would disappear after 10 seconds
- If no title is provided by the developer for the transaction, the heading of the transaction notification should be a shortened version of the transaction ID (Transaction 0x2348...) and description will e the status.
- When I click on the transaction notification, I will be taken to the transaction details on flowscan in a new window

Design:
- [right placement](https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper---Flow---Designs?node-id=1266%3A328)
- [3 pending - expanded](https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper---Flow---Designs?node-id=1266%3A982)
- [Mobile - Open](https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper---Flow---Designs?node-id=1331%3A14)
- [Mobile - Closed](https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper---Flow---Designs?node-id=1329%3A11)

---
Original ticket:

We'd like to improve the progress indicator for transactions.
- Progress indicator should be global and persist across page navigations
    - Otherwise error messages can be lost (and success messages)
- Could we have a dedicated transaction status React component?
- Related, but the notification toast is not super obvious
    - It also shouldn't bump the rest of the UI up upon close
    - Could we integrate the notification into the status component?
- Ideally supports multiple transactions (queue)

Requires design.

**Comment by PeterArbaugh** [comment]
Confirmed decision 2/17 to save to localStorage without tab sync.

> Pending transactions are saved, and other tabs have to be refreshed to see any new transactions

**Comment by MrDSGC** [comment]
Closing since issue has been resolved
