### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by avpdiver** [onflow/kitty-items#184]
**Describe the bug**
I have tried dev and testnet. Both produce the same error when opening http://localhost:3001/

**Screenshots/Logs/Output**
![image](https://user-images.githubusercontent.com/1391973/148978762-e6059be9-9715-4bdf-88a9-47ceb4d9f200.png)

**Environment (Optional - Version, OS, Browser, etc.)**
Ubuntu 20.04
NodeJS v16.13.2
NPM 8.3.0
Docker 20.10.7
Docker Compose v2.2.3
Flow v0.30.2

**Comment by kerrywei** [comment]
@avpdiver I can't reproduce this locally (I wiped out my local env and started all over). could you confirm you did step 2 "flow project deploy --network emulator" to deploy all contracts to emulator?

**Comment by avpdiver** [comment]
For _testnet_ I did: 
`flow project deploy --network testnet -f flow.json -f flow.testnet.json`

And response was:
`Deploying 1 contracts for accounts: testnet-account`
`KittyItems -> 0xfa583cca33ef2467 (4d647f95fce4fd4a1791ec4845df55c66a43daa8e41fe7a47f56e958810f5e2a)`
`✨ All contracts deployed successfully`

**Comment by fluffywiggle** [comment]
I am getting the same exact errors after following all the steps for Testnet Development. 
![image](https://user-images.githubusercontent.com/6555812/149242593-1a24ef42-17c1-4b8b-84bc-d455be24ff1e.png)

**Comment by avpdiver** [comment]
Local development doesn't work as well.
`flow project deploy --network emulator` returns
```
Deploying 3 contracts for accounts: emulator-account

❌ Error deploying NonFungibleToken: (execution error code 1006: [Error Code: 1006] invalid proposal key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: signature is not valid)

❌ Error deploying KittyItems: (execution error code 1006: [Error Code: 1006] invalid proposal key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: signature is not valid)

❌ Error deploying NFTStorefront: (execution error code 1006: [Error Code: 1006] invalid proposal key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: signature is not valid)

❌ failed to deploy all contracts
❌ Command Error: failed to deploy all contracts
```

And dev-wallet produce an error:
```
TX:ERROR Error: address d3aed690bfd0b9b7 is invalid for chain flow-emulator
    at Object.onEnd (/app/node_modules/@onflow/sdk/dist/sdk.js:1:10252)
    at /app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24233
    at /app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11490
    at Array.forEach (<anonymous>)
    at e.rawOnError (/app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11452)
    at e.onTransportHeaders (/app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:9025)
    at NodeHttp.responseCallback (/app/node_modules/@improbable-eng/grpc-web-node-http-transport/lib/index.js:31:22)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
```

**Comment by avpdiver** [comment]
Fixed
