### ISSUE TITLE
Admin account setup should happen in command line, not web app

### ISSUE THREAD

**Issue by psiemens** [onflow/kitty-items#186]
When running Kitty Items locally, the developer does the following:

1. Starts the emulator, dev wallet, web app and API
2. Uses the Flow CLI to deploy the necessary contracts to the emulator 
3. Opens the web app and initializes the admin account for minting

The problem is that step 3 is only possible when running the app locally. It does not work when moving to testnet or mainnet. This is because the local "admin account" is the service account by default, which can be accessed through the dev wallet. Therefore the web app can use FCL and the dev wallet to run the initialization transaction.

When deploying to testnet, most developers will create their own admin account that they control from the CLI or other tools. We should show them how to initialize this account using local tooling rather than through the UI.

My suggestion is to convert step 3 to a simple CLI command and remove the UI prompts. This will show developers how to manage their testnet and mainnet accounts, and results in an onboarding workflow that is the same across all networks.

**Comment by alxflw** [comment]
I'm in favor of this as well. @psiemens who could be assigned to this and in which sprint might we get to it?

**Comment by psiemens** [comment]
Nice, looks like we've got Mack pencilled in for this one. 👍

**Comment by 10thfloor** [comment]
@psiemens just to clarify, 
We want a command like `ki bootstrap-admin --testnet` that prompts for the testnet account and key?

**Comment by psiemens** [comment]
@10thfloor I don't think we need any new commands. This should all be possible with the CLI.

For emulator:

```sh
flow transactions send --signer emulator-account ./cadence/transactions/setup-admin-account.cdc
```

For testnet:

```sh
flow transactions send --signer testnet-account ./cadence/transactions/setup-admin-account.cdc
```

The transaction `/cadence/transactions/setup-admin-account.cdc` doesn't exist at that location -- it currently lives here: https://github.com/onflow/kitty-items/blob/master/web/cadence/transactions/initialize_account.cdc

I would recommend we move that file to `./cadence/transactions/setup-admin-account.cdc` because it will no longer be needed by the frontend. I also recommend renaming it to `setup-admin-account.cdc` to be consistent with the other `setup-account.cdc` transactions and to clearly indicate that it's only for the admin account.
