### ISSUE TITLE
Error when trying to mint on Testnet

### ISSUE THREAD

**Issue by fluffywiggle** [onflow/kitty-items#196]
When trying to mint a new item in Testnet I get the following error: 
`useMintAndList.js?0e5d:11 
Uncaught (in promise) [Error Code: 1101] cadence runtime error Execution failed:
error: assertion failed: Missing or mis-typed KittyItems.Collection provider
  --> e9f947d8d4adead585ebcbc4b17f865af466540f2974a1b886e5d0ecdc66aaf9:39:8
   |
39 |         assert(self.kittyItemsProvider.borrow() != nil, message: "Missing or mis-typed KittyItems.Collection provider")`

![image](https://user-images.githubusercontent.com/6555812/149997360-f7787159-40db-41fe-8161-0b273699ad28.png)

**Comment by alse** [comment]
@fluffywiggle looks like the service account needs to be initialized, have a look at this [comment](https://github.com/onflow/kitty-items/issues/164#issuecomment-1010432246)

**Comment by 10thfloor** [comment]
@fluffywiggle Yes, the steps listed in the issue should help you solve this issue. Let us know if it does not so we can help you get up and running.

**Comment by MrDSGC** [comment]
closing outdated issue. Let us know if you are still experiencing this error!
