### ISSUE TITLE
error tracking integration

### ISSUE THREAD

**Issue by kerrywei** [onflow/kitty-items#204]
**Is your feature request related to a problem? Please describe.**
We lack of the capability of error reporting for the heroku based app, leaving us in a state where we rely on users to report such errors. To be able to proactively identify & address problems, it's recommended to leverage a modern error tracking system

**Describe the solution you'd like**
Sentry could be a good fit for this purpose; open to using any other tools that are easy to integrate & can achieve the goal

**Comment by MrDSGC** [comment]
closing since app has been added to sentry
