### ISSUE TITLE
Add metrics to track usage

### ISSUE THREAD

**Issue by alxflw** [onflow/kitty-items#206]
We would like to track how this project is used once it is released. 

**What should we track**
I'd suggest we align briefly on this. In my mind, the project has a few success milestones. The more developers we get converted to the last milestone, the better.

1. Project is discovered by dev
2. Project demo is used
2. Project is running successfully locally
3. Project is usable locally (at least initialization + minting works)
4. Project is configured for testnet
5. Project is deployed on testnet
6. Project is usable on testnet (Auth works)
7. Project is deployed on Heroku

**How we should track**
I'm not too familiar with our existing telemetry capabilities, but here are ideas I'd like to get feedback on. We should only capture # of devs per stage, anonymized. 

1. Discovery: # of visitors on a docs page we consider the starting point (alternative: GitHub repo visits)
2. Demo usage: # of website visitors (tracked via eg [Fathom](https://usefathom.com/))
2. Local running: # of docker image downloads? (likely influenced by unrelated downloads)
3. Local usable: unclear (maybe possible to re-use the demo tracking)?
4. Configured for testnet: # of faucet visitors with specific UTM parameter (set in in the readme/docs URLs)
5. Deployed on testnet: # of `KittyItems` contracts deployed
6. Usable on testnet: # of `KittyItems.NFTMinter` transactions processed
7. Deploy to Heroku: # of of docs page visitors with UTM parameter (set as success url [`app.json` file](https://devcenter.heroku.com/articles/app-json-schema#success_url))

thoughts @srinjoyc @psiemens @10thfloor ?

**Comment by srinjoyc** [comment]
@alxflw - we should discuss adding some Mixpanel metrics on the testnet deployment to measure general usage of features/pages on the dapp.

**Comment by psiemens** [comment]
> Discovery: # of visitors on a docs page we consider the starting point (alternative: GitHub repo visits)

We can definitely use the built-in GitHub traffic for this. I'd recommend we track number of visits to this repository (we don't have a dedicated docs page for Kitty Items)

> Demo usage: # of website visitors (tracked via eg Fathom)

Yep, we can add basic analytics to the demo site

> Project is running successfully locally

This is a tricky one. Maybe we can start with # of repository clones?

> Deployed on testnet: # of KittyItems contracts deployed

Yep, we can get this data with existing tooling

> Usable on testnet: # of KittyItems.NFTMinter transactions processed

Unsure if we have the tooling to see this, but it is possible

**Comment by alxflw** [comment]
I preparation for our meeting today, I took a stab at the minimal set of metrics that might be useful:

- [x] Discovery: # of visitors on the tutorial
- [ ] Demo usage: # of visitors on deployed Heroku app (need to set up)
- [x] Local usage: # of clones on GitHub
- [x] Configured for testnet: # of faucet visitors originating from the tutorial (need access @srinjoyc)
- [ ] (TBD) Deployed on testnet: # of KittyItems contracts deployed
- [ ] (TBD) Usable on testnet: # of KittyItems.NFTMinter transactions processed

Let's discuss!

**Comment by sideninja** [comment]
@alxflw @srinjoyc I documented the metrics related task and the plan here https://github.com/onflow/devex-metrics/issues/12
