### ISSUE TITLE
Add the new FCL discovery mechanism to Kitty Items

### ISSUE THREAD

**Issue by srinjoyc** [onflow/kitty-items#213]
Currently, when Kitty Items uses FCL discovery, it shows both Ledger & Blocto. Ledger does not work with Kitty items and should be removed as an option.

This can be done by updating to the latest FCL which will automatically remove ledger but will only show Blocto. To avoid this we can use the new FCL discovery mechanism to replace the log in button programmatically with the discovery API. See [link](https://docs.onflow.org/fcl/reference/api/#discovery-1).

**Comment by 10thfloor** [comment]
This has been removed pending further improvements by @chasefleming 
cc @kerrywei @srinjoyc Can we move this to closed or backlog?

**Comment by chasefleming** [comment]
Just want to note the programmatic way of using Discovery API over UI is not the only way to remove Ledger. Upgrading FCL will also remove Ledger from the UI modal unless explicitly told to include it in the config.

**Comment by 10thfloor** [comment]
This issue has been removed from the sprint.
