### ISSUE TITLE
Don't require docker for the basic installation

### ISSUE THREAD

**Issue by srinjoyc** [onflow/kitty-items#214]
**Problem**
Docker adds a lot of overhead and friction when getting started with Kitty Items, we should find a easier way to run Kitty Items ideally without docker especially when developing against testnet.

**Suggest Solutions**
- During the "Testnet" steps of the readme, potentially start the client-side that is connected to a pre-deployed server
- Start multiple processes in a user-friendly way via a single command without docker.

**Comment by 10thfloor** [comment]
Investigating using [sqlite3 ](https://www.npmjs.com/package/better-sqlite3) + [pm2](https://pm2.keymetrics.io/) as a replacement for the docker images. 

sqlite plugs into the ORM, and I already have it working. 
PM2 is a well know multi-process manager for node apps, and has strong configuration management story. 
App can be started using an `package.json` script.

**Comment by 10thfloor** [comment]
The only Dockerized aprt of KittyItems I;m not sure about how to replace is the dev-wallet. 
Currently we'd need to include the dev-wallet code in the project source code. 

I know @psiemens was experimenting with a static build of the dev-wallet.

It would be excellent if the dev-wallet were included and served via the emulator / cli.

**Comment by 10thfloor** [comment]
cc @alxflw @srinjoyc

**Comment by kerrywei** [comment]
@10thfloor could you provide a status update this task?

**Comment by 10thfloor** [comment]
Docker has been removed, but this is blocked by: https://github.com/onflow/flow-cli/issues/463
Once the dev-wallet is integrated, we can release this.

**Comment by 10thfloor** [comment]
PR is here: https://github.com/onflow/kitty-items/pull/221
