### ISSUE TITLE
Create `kitty-items.onflow.org` and point to Heroku deployment

### ISSUE THREAD

**Issue by alxflw** [onflow/kitty-items#228]

**Comment by psiemens** [comment]
The DNS record is set up for `kitty-items.onflow.org` to point to the Heroku app. However, I'm blocked on configuring the Heroku app because I don't have admin access. I will reach out to gain access.

**Comment by alxflw** [comment]
thanks!

**Comment by psiemens** [comment]
I've opened an IT request to have this custom domain added to the Heroku deployment.

**Comment by MrDSGC** [comment]
Closing since issue has been resolved
