### ISSUE TITLE
Homepage: Initial page to explain project and what to do next

### ISSUE THREAD

**Issue by alxflw** [onflow/kitty-items#232]
For a fresh installation of KI, the homepage will be empty. We would like to use it to orient the developer.

### Copy

Here is what I suggest we show on this page:

```
<h1>Welcome to Kitty Items: A CryptoKitties Sample App</h1>

Your marketplace is currently empty. Get started by <a>minting your first kitty items</a>.


<p><a>Learn more about the key components and services that make Kitty Items possible.</a></p>
```

### Design

In addition to the copy, we would like to design the page itself:

- [ ] Tanooki to propose a design (we can review async)
- [ ] Tanooki to implement the design once reviewed

### Questions

Should the banner on top ("mint kitty items") still be shown? Likely redundant. I lean towards removing it.

**Comment by LaurenIke** [comment]
Hi @alxflw please find below a few design options for review: 

light box option - https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper---Flow---Designs?node-id=1444%3A17

full page option - https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper---Flow---Designs?node-id=1449%3A23

Let us know if one or the other is preferred and if there are any requested changes!

**Comment by alxflw** [comment]
@10thfloor @srinjoyc any thoughts on this? I think Mack was leaning towards the full page option

**Comment by alxflw** [comment]
during the meeting we agreed on moving forward with the full page option

**Comment by MrDSGC** [comment]
Closing since issue has been resolved
