### ISSUE TITLE
Code now requires Secure Cadence

### ISSUE THREAD

**Issue by turbolent** [onflow/kitty-items#246]
**Describe what is not documented**

With #245 merged, the code in the repo requires Secure Cadence, which is not released yet.

**Suggested Solution**

Maybe tag the commit before #245 was merged and publish a release, then add a note to the README pointing to the tag.
Once Secure Cadence has been deployed to Testnet and Mainnet, the note can be removed.

**Comment by alxflw** [comment]
@srinjoyc @10thfloor - could you review and see if/when this could be prioritized?

**Comment by MrDSGC** [comment]
Closing issue since secure cadence has been released (v0.24)
