### ISSUE TITLE
kitty-items marketplace is not starting on testnet 

### ISSUE THREAD

**Issue by sonerkoylu** [onflow/kitty-items#247]
Hi.
We want to review kitty-items marketplace. We installed env. tools and then we want to start on dev testnet. We took an error like this:

`⠖ Deploying contracts to:  0xf8d6e0586b0a20c7 (emulator)node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: flow project deploy -o json --network=emulator -f flow.json --update
 Command Error: failed to deploy all contracts
    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'flow project deploy -o json --network=emulator -f flow.json --update',
  stdout: '\n',
  stderr: ' Command Error: failed to deploy all contracts'
}`

We want to review kitty-items.

![image](https://user-images.githubusercontent.com/11064802/171352916-a3f7cee4-1f4c-4196-b75c-f82b42a72c87.png)

`PS D:\sources\flow\kitty-items> flow version
Version: v0.34.0
Commit: 6c240a76ec2bb5d5685afeb0898eed0ea1bd0059
PS D:\sources\flow\kitty-items> npm --version`

**Comment by MrDSGC** [comment]
Hi @sonerkoylu , try updating your flow-cli & kitty items repo to the latest version. Your error may have been addressed in a recent update.
