### ISSUE TITLE
KittyItems: staging environment

### ISSUE THREAD

**Issue by MrDSGC** [onflow/kitty-items#250]
## Context

Create a staging environment in herkou for kittyitems to allow for better testing workflow for future deploys

## Definition of Done

- [x]  staging environment created in heroku
- [x] kittyitems deployed to staging
- [x] update internal documentation to reference staging environment

**Comment by MrDSGC** [comment]
> @MrDSGC is internal documentation updated to reflect this new staging environment?

Not yet. Do you know where i would need to make the updates internally?

**Comment by kerrywei** [comment]
@MrDSGC there might not be an existing doc yet. do you think this is worth to be documented? if so, we can start something new (in this repo ideally, or a new Notion doc)

**Comment by MrDSGC** [comment]
created notion subpage doc under Engineering Processes on team page.
