### ISSUE TITLE
issues on ubuntu 20.04

### ISSUE THREAD

**Issue by DramaCrypto** [onflow/kitty-items#261]
I installed Flow CLI and node js
Next I execute `npm run dev:testnet`

but issues happened like below : 
---------------------------------------

> kitty-items@1.0.0 dev:testnet
> npx cross-env CHAIN_ENV=testnet node .ki-scripts/startup.js

ℹ Stopping previously launched processes...

xargs -
Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by bluesign** [comment]
not a solution but as a workaround you can comment out: https://github.com/onflow/kitty-items/blob/74b0b58fdf89560ac65e11e740c08bf0410db5eb/.ki-scripts/startup.js#L134
