### ISSUE TITLE
issues on windows

### ISSUE THREAD

**Issue by DramaCrypto** [onflow/kitty-items#262]
After execute `npm run dev:testnet`

---------------------------------------------

PM2      | App [api:0] starting in -fork mode-
0|api    | TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".CMD" for D:\FLOW_DEV\KITTY-ITEMS\NODE_MODULES\.BIN\NPM.CMD
0|api    |     at new NodeError (node:internal/errors:371:5)
0|api    |     at Object.file: (node:internal/modules/esm/get_format:72:15)
0|api    |     at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
0|api    |     at defaultLoad (node:internal/modules/esm/load:13:42)
0|api    |     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
0|api    |     at new ModuleJob (node:internal/modules/esm/module_job:63:26)
0|api    |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
0|api    |     at async Promise.all (index 0)
0|api    |     at async ESMLoader.import (node:internal/modules/esm/loader:281:24) {
0|api    |   code: 'ERR_UNKNOWN_FILE_EXTENSION'
0|api    | }

**Comment by bluesign** [comment]
There is a workaround: https://github.com/onflow/kitty-items/issues/241#issuecomment-1144726795

**Comment by MrDSGC** [comment]
Issue should be resolved here #268
