### ISSUE TITLE
Testnet demo broken #hackathon

### ISSUE THREAD

**Issue by yosun** [onflow/kitty-items#317]
**Describe the bug**
[A clear and concise description of what the bug is.](https://kitty-items.flow.com/) is borked
 
**To Reproduce**

Visit site above

**Expected behavior**

Heroku should not say it is Application Error borked 

**Screenshots/Logs/Output**

[![Image from Gyazo](https://i.gyazo.com/65c07b3dc30dab11c66a3bf806053271.png)](https://gyazo.com/65c07b3dc30dab11c66a3bf806053271)

**Environment (Optional - Version, OS, Browser, etc.)**

All browsers.

**Additional context (Optional - Anything else about the bug)**

**Comment by nvdtf** [comment]
This was running on a free Postgres plan and was impacted due to https://blog.heroku.com/next-chapter
Should be up and running now
