### ISSUE TITLE
Dark mode diagram

### ISSUE THREAD

**Issue by 10thfloor** [onflow/kitty-items#323]
The architecture overview isn't viewable if you're using GitHub's dark mode. Well, it's viewable, but just barely. 

<img width="1381" alt="Screenshot 2023-09-05 at 8 21 16 AM" src="https://github.com/onflow/kitty-items/assets/901466/53cf2618-978f-4c77-8a1a-6c761dd2bb87">

**Comment by joshuahannan** [comment]
closing because we are archiving in favor of the [flow app quickstart](https://developers.flow.com/build/guides/flow-app-quickstart)
