### ISSUE TITLE
Readme git clone command fix

### ISSUE THREAD

**Issue by sideninja** [onflow/kitty-items#38]
It might be better to change `git clone` command in the readme to use HTTPS as it doesn't require ssh keys and in some cases, users might not have one generated.
From
```
git clone git@github.com:onflow/kitty-items.git
```
To
```
git clone https://github.com/onflow/kitty-items.git
```

Read more: https://docs.github.com/en/github/using-git/which-remote-url-should-i-use

**Comment by 10thfloor** [comment]
Agreed. Will change this in the next release.

**Comment by psiemens** [comment]
Fixed!
