### ISSUE TITLE
Error in KittyItemsMarket Contract

### ISSUE THREAD

**Issue by Jacobclaerhout** [onflow/kitty-items#39]
When running the Kitty Deployer, I keep getting the error below, which keeps the KittyItemsMarket contract from being created. Am I doing something wrong here? Have unsuccessfully tried a couple of things to make this work.

```
add contract name: KittyItemsMarket
error Execution failed:
error: cannot deploy invalid contract
 --> d2b04695922cc6c53d535932b0dafcf61835596fb531669702cad72b0d723676:7:12
  |
7 |             self.signer.contracts.add(
  |             ^

error: unexpected token: identifier
 --> 3e9a346a9ab99a73.KittyItemsMarket:1:22
  |
1 | import Kibble from 0x0x3e9a346a9ab99a73
  |                       ^
 undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitty-items-deployer@0.0.1 start:dev: `tsnd src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kitty-items-deployer@0.0.1 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
```

**Comment by robmyers** [comment]
Looking at the error there's a double 0x0x in the code where the caret is pointing to:
```
1 | import Kibble from 0x0x3e9a346a9ab99a73
  |                       ^
```

We're updating the tutorials to use the new cli deployer capabilities, that might be easier to use.

**Comment by robmyers** [comment]
The new version has been merged to the repository. If you pull the latest version you can now deploy with
```
flow project deploy --network=testnet
```
Can you try that and let me know how it goes?

**Comment by psiemens** [comment]
This seems to be working now 👍
