### ISSUE TITLE
Spotted an inaccuracy in "./kitty-items-deployer/README.md"

### ISSUE THREAD

**Issue by Johnrobmiller** [onflow/kitty-items#40]
There is an error in the README.md file in "./kitty-items-deployer".  It instructs devs to install dependencies using "npm install", but the author forgot to mention first to cd into "./kitty-items-deployer" before doing so.  People who are unfamiliar with npm commands and the package.json file will most likely get stuck here.

EDIT: On a related note, it might also be useful to describe in further detail how the .env file should be formatted.  I made the mistake of first doing this: `ACCOUNT_ADDRESS={0x6adc3ecc434e6afe}`.  Then, I changed it to this: `ACCOUNT_ADDRESS={6adc3ecc434e6afe}`.  Finally, I figured out that it was this: `ACCOUNT_ADDRESS=6adc3ecc434e6afe`.  In my opinion, it's ok to add lots and lots of detail to a readme, even if, for most devs, that detail is superfluous.  A bit of hand-holding never hurt anybody, after all.

**Comment by psiemens** [comment]
Thanks for the feedback! This is really helpful.

We actually have an update to all of this coming in short order, but this helps make sure we keep the new README clear, too.

**Comment by psiemens** [comment]
Closing as the `kitty-items-deployer` directory has been removed and replaced with the `flow project deploy` command.
