### ISSUE TITLE
"Items Shop" loading forever after listing items from "My Items"

### ISSUE THREAD

**Issue by miaoqiz** [onflow/kitty-items#43]
Hi there,

Thanks for the excellent example!

After listing the items from "Items Shop", are these items supposed to go back and show up under the "Items Shop" tab?

If so, the page has been loading forever ( a spinning circle by ID), although the items in "My Items" tab have been updated. 

Thanks so much and have a good day!

**Comment by 10thfloor** [comment]
Another one. This should be fixed when we merge this PR #27

**Comment by 10thfloor** [comment]
Fixed by #27
