### ISSUE TITLE
Cannot see items from "Items Shop" after click "List for 10 KIBBLE"

### ISSUE THREAD

**Issue by chenbingyu00** [onflow/kitty-items#45]
When I clicked "List for 10 KIBBLE"，the status of the item changed to "Unlist", but the item didn't show up in the "Items Shop". Any help is appreciated. Thanks.

**Comment by 10thfloor** [comment]
Thanks for creating an issue! 
This should be fixed when we merge this PR https://github.com/onflow/kitty-items/pull/27

**Comment by 10thfloor** [comment]
Fixed by #27
