### ISSUE TITLE
Import transactions/scripts into JS rather than inlining them

### ISSUE THREAD

**Issue by shubik22** [onflow/kitty-items#47]
In `web/src/flow`, all the transactions/scripts are inlined as strings.  I think a better option is to save them as cdc files in the `cadence/scripts` `cadence/transactions` directories and then import them into the JS.  The way I achieved this in the project I'm working on (which I forked off of `kitty-items`) is via https://github.com/pveyes/raw.macro.

So instead of:

```
const CODE = fcl.cdc`
  import FungibleToken from 0xFungibleToken
  ...
`
```

You'd have:

```
import raw from "raw.macro";;
const script = raw("../../../cadence/scripts/is_account_initialized.cdc");
const CODE = fcl.cdc`${script}`
```

The primary benefits are 1) testability (you can test your scripts/transactions in go) and 2) readability (the transactions/scripts are easier to read in cdc files than just long strings in JS files).

If the Flow team likes this idea and is willing to accept outside contributions to this repo, I'd be happy to put together a PR making this change.

**Comment by 10thfloor** [comment]
Awesome. I think this would be a good idea. 
I would create a separate folder for the "web' scripts vs the 'api' scripts. What does your cadence folder structure look like?

**Comment by shubik22** [comment]
In my own project, I currently just have subfolders depending on the Contract that each script/transaction is associated with:

cadence
cadence/contracts
cadence/transactions
cadence/transactions/gambit
cadence/transactions/chess_stars_market
cadence/transactions/chess_stars
cadence/scripts
cadence/scripts/gambit
cadence/scripts/chess_stars_market
cadence/scripts/chess_stars

Happy to create web/api folders in kitty-items if you think that'd be a good structure.

**Comment by alxflw** [comment]
@psiemens I would like to take this one on
