### ISSUE TITLE
Consider using foreman

### ISSUE THREAD

**Issue by shubik22** [onflow/kitty-items#48]
Given there are multiple processes in this application, it might make sense to create a Procfile and use [Forman](https://github.com/strongloop/node-foreman).

A simple Procfile.dev would be:

```
web: cd web && npm run start:dev
worker: cd api && npm run start:dev
```

Then users could start the application (after having set up the necessary dependencies) by running `nf start -j Procfile.dev` from the root of the repository.

I'd be happy to put out a PR making this change if the Flow team supports this idea.

**Comment by 10thfloor** [comment]
We have a 'consolidated' startup using `concurrently` in the root of the project. Procfiles could be a good road to a Heroku deployment. 
Would love to make this deployable to Heroku. Any thoughts?

**Comment by shubik22** [comment]
That would be fun.  I'd imagine the best way to do that would be with a Deploy To Heroku button ([docs](https://devcenter.heroku.com/articles/heroku-button)).  Happy to look into how to set this up if you like the idea.

**Comment by 10thfloor** [comment]
> That would be fun. I'd imagine the best way to do that would be with a Deploy To Heroku button ([docs](https://devcenter.heroku.com/articles/heroku-button)). Happy to look into how to set this up if you like the idea.

Love the idea. I have looked into it briefly. It looks like there might be some extra config because there are actually 2 separate apps in the project. (The server does not serve the html SPA).

I suppose we could set up the server to also handle the SPA.

It would be very cool to have a one-button deploy for this app.

**Comment by 10thfloor** [comment]
OK, check this out: https://github.com/onflow/kitty-items/pull/54
