### ISSUE TITLE
Contract deploy error

### ISSUE THREAD

**Issue by DubovkaE** [onflow/kitty-items#49]
When i use "flow project deploy --network=testnet" i get
Deploying 3 contracts for accounts: emulator-account,testnet-account
Kibble error
KittyItems error
KittyItemsMarket error

❌ Failed to deploy all contracts

**Comment by 10thfloor** [comment]
@DubovkaE Can you provide a bit more context? 
This probably means that you haven't properly exported the environment variable to your shell, as mentioned here: 
https://github.com/onflow/kitty-items#save-your-keys

**Comment by 10thfloor** [comment]
Closed by #82
