### ISSUE TITLE
Live demo: CORS problems

### ISSUE THREAD

**Issue by nduplessis** [onflow/kitty-items#50]
Hello

The live demo app from the readme in this repo is broken in most major browsers as far as I can tell, this includes:

- Firefox
- Safari
- Edge

<img width="1218" alt="Screenshot 2021-03-29 at 18 48 02" src="https://user-images.githubusercontent.com/159896/112871930-1081e180-90c0-11eb-8d51-7b31f59b0633.png">

**Comment by 10thfloor** [comment]
Hmm, 
- I see you're deploying on Heroku? Could this be a Heroku CORS configuration issue? 
- What does your CSP configuration look like for the front-end app?

**Comment by nduplessis** [comment]
This isn't my deployment, this is the link in the readme to the live demo app

**Comment by 10thfloor** [comment]
Nice, ok, I'll check out our deployment. Thanks for flagging.

**Comment by 10thfloor** [comment]
Fixed.
