### ISSUE TITLE
Deploy new Kitty Items demo API and events worker to Heroku

### ISSUE THREAD

**Issue by psiemens** [onflow/kitty-items#52]
## Context

PR https://github.com/onflow/kitty-items/pull/27 merges in updates that require the events worker to always been running.

The current Heroku deployment does not include a dyno for the events worker.

## Suggest a Solution

Create a `Procfile` with the following entries ([inspired by this comment](https://github.com/onflow/kitty-items/issues/48#issue-842177382)):

```
web:    node api/dist/index.js
worker: node api/dist/index.js --worker
```

This requires a change to the `api` project to make the worker to be runnable as a separate process. 

## Definition of Done

- [ ] `kitty-items/api` is updated to allow for separate API and worker processes
- [ ] `Procfile` is created with `web` and `worker` entries
- [ ] Demo Heroku deployment has been updated with the new `Procfile`

**Comment by 10thfloor** [comment]
Nice. I can add this as part of https://github.com/onflow/kitty-items/pull/54 as well!
