### ISSUE TITLE
When login, rpc error: code = Internal desc = failed to execute script

### ISSUE THREAD

**Issue by balibou** [onflow/kitty-items#57]
Hello,

I have followed the tutorial and I am currently on the frontend part. When I try to login on the app I get this;
I am trying to figure out but I'm really stuck:

<img width="1178" alt="Screenshot 2021-04-01 at 19 23 50" src="https://user-images.githubusercontent.com/7440159/113331255-02ca9700-9320-11eb-9346-e58f9b2188ae.png">

Thanks for any help provided !

**Comment by kulame** [comment]
it looks like some bug occur in Cadence scripts
