### ISSUE TITLE
Add context to FE demo application

### ISSUE THREAD

**Issue by psiemens** [onflow/kitty-items#6]
The current Kitty Items FE application ([viewable here](https://kitty-items.on.fleek.co/#/)) contains all of the desired functionality but is still hard to understand without looking at the underlying code and contracts.

What minimal updates can we make to the application UI to better illustrate the logic of Kitty Items _and_ the core concepts of Flow?

**Comment by jordankitty** [comment]
User stories and designs will live here: https://www.notion.so/dapperlabs/138a7bc1800b46fe80f65604ada3d522?v=55f7fc09c00a4c2ba865048efc2727af

We can address the lack of context by alerting on user state - no kibble, no account initialized. Still need to brush up the designs and do a quick pass at definition. Still WIP!

🎩
😸

![image](https://user-images.githubusercontent.com/37638382/105918362-a7f78500-5fe8-11eb-9666-b0ee5f341e46.png)

**Comment by psiemens** [comment]
@jordankitty This is already looking great! The "Get Kibble" callout is super clear 💯

**Comment by yungcloud** [comment]
Hey guys, really interested in this, I'm trying the demo... after signing-in I see some elements, a spinning wheel, then a blank page. Have tried in few browsers

**Comment by 10thfloor** [comment]
> Hey guys, really interested in this, I'm trying the demo... after signing-in I see some elements, a spinning wheel, then a blank page. Have tried in few browsers

Hey @yungcloud We're getting around to fixing it this week. Sorry for the issues.

**Comment by 10thfloor** [comment]
> > Hey guys, really interested in this, I'm trying the demo... after signing-in I see some elements, a spinning wheel, then a blank page. Have tried in few browsers
> 
> Hey @yungcloud We're getting around to fixing it this week. Sorry for the delay.

Should be fixed now. :)
