### ISSUE TITLE
Data member mismatch 

### ISSUE THREAD

**Issue by miaoqiz** [onflow/kitty-items#60]
Hi there,

I ran the current code and encountered the error:

---------------------------------------------------------------------------------------------------------------------------

Error: failed to execute the script on the execution node: rpc error: code = Internal desc = failed to execute script: failed to execute script at block (8b8117acdc3f29c123531ecd493a5248ad911977256c55fec16b60eb5ae785bb): Execution failed:
error: incorrect argument label
  --> c8bea33ade24cd3394b73ba9dc7656c10e059d6f4b97358b1aa24c33a35df9c5:20:50
   |
20 |           if let item = collection.borrowSaleItem(itemID: id) {
   |                                                   ^^^^^^ expected `saleItemID`, got `itemID`

error: value of type `&KittyItemsMarket.SaleOffer{KittyItemsMarket.SaleOfferPublicView}` has no member `typeID`
  --> c8bea33ade24cd3394b73ba9dc7656c10e059d6f4b97358b1aa24c33a35df9c5:21:53
   |
21 |             return SaleItem(itemID: id, typeID: item.typeID, owner: address, price: item.price)
   |                                                      ^^^^^^ unknown member

error: value of type `&KittyItemsMarket.SaleOffer{KittyItemsMarket.SaleOfferPublicView}` has no member `price`
  --> c8bea33ade24cd3394b73ba9dc7656c10e059d6f4b97358b1aa24c33a35df9c5:21:89
   |
21 |             return SaleItem(itemID: id, typeID: item.typeID, owner: address, price: item.price)
   |                                                                                          ^^^^^ unknown member
onEnd
src/send/unary.js:11
   8 | grpc.unary(method, {
   9 |   request: request,
  10 |   host: host,
> 11 |   onEnd: ({status, statusMessage, message}) => {
     | ^  12 |     if (status === grpc.Code.OK) {
  13 |       resolve(message)
  14 |     } else {
View compiled
▶ 4 stack frames were collapsed.
NodeHttp.responseCallback
src/index.ts:36
  33 |     _this.options.debug && console.log("NodeHttp.data", chunk);
  34 |     _this.options.onChunk(toArrayBuffer(chunk));
  35 | });
> 36 | response.on("end", function () {
     | ^  37 |     _this.options.debug && console.log("NodeHttp.end");
  38 |     _this.options.onEnd();
  39 | });
View compiled
▶ 3 stack frames were collapsed.

---------------------------------------------------------------------------------------------------------------------------

Can you kindly advise how to fix the issue?

Thanks so much and have a good day!

Mio

**Comment by 10thfloor** [comment]
We cleaned up and shortened the names of properties in the latest update. @miaoqiz 
You should be able to safely rename `saleItemID` to `itemID` wherever you find it. Not sure how this one slipped through.
