### ISSUE TITLE
Deploy the contracts but don't get any contracts

### ISSUE THREAD

**Issue by Ericchen0108** [onflow/kitty-items#63]
Hi there,
today I follow the step and deploy the contracts,
but I don't get any contracts
![1618396751413@2x](https://user-images.githubusercontent.com/43982345/114703873-7c1eac80-9d58-11eb-8e3e-6fab38345aef.jpg)

Is it correct or I miss some steps?

**Comment by kulame** [comment]
try the command flow accounts get {address} --network=testnet
then you can watch your contracts in your account.

**Comment by srinjoyc** [comment]
Make sure your `flow.json` file has "contracts" inside it (is non empty). I ran `flow init` early and it replaced the original flow.json file.

**Comment by Ericchen0108** [comment]
Thanks @kulame @srinjoyc 
I found that I changed the` flow.json` files coz I ran `flow init` and it replaced the original one...
Now I changed it back and it worked!
