### ISSUE TITLE
Add additional context to README

### ISSUE THREAD

**Issue by psiemens** [onflow/kitty-items#7]
The current README provides a good overview of the application, but it should provide more information about the core concepts of Flow.

For example:
- How does the Flow account model work?
- What is Cadence and what is it for?
- What is the Flow emulator and how does it fit into the development workflow?
- What is the Flow Testnet and how can it be accessed?

**Comment by 10thfloor** [comment]
I imagine we can provide links where relevant, instead of writing fresh content?

**Comment by psiemens** [comment]
> I imagine we can provide links where relevant, instead of writing fresh content?

Yep, definitely. Ideally this also pushes us to fill holes in the documentation site along the way.

**Comment by 10thfloor** [comment]
![Kitty Items Outline](https://user-images.githubusercontent.com/901466/106841952-f4316d80-6657-11eb-8853-870e08a058e5.png)

**Comment by 10thfloor** [comment]
Closed by #11
