### ISSUE TITLE
[Testing] Add basic tests to demonstrate JS testing library

### ISSUE THREAD

**Issue by srinjoyc** [onflow/kitty-items#71]
### Why
Currently, we don't have any usage of our JS testing library in this keystone example to demonstrate how the integration works.

### What (Definition of Done)

Add the following basic tests:
1. Account creation: Multiple accounts can be created 
2. Contract deploy: Deploys all contracts one by one in the cadence folders.
3. Transaction to mint kibble. 
4. Transaction to mint kitty-item
5. Transaction to transfer kitty-item

Add documentation to the README explaining the testing and link out to remaining testing docs on the testing repo. https://github.com/onflow/flow-js-testing

**Comment by 10thfloor** [comment]
@MaxStalker

**Comment by MaxStalker** [comment]
@10thfloor I think we covered this one. The only problem we have right now is failing tests in CI environment.
I was not able to find a stable solution, but one of the community members reported that they might have a clue :)
So I'm waiting for their response to fix it everywhere.

**Comment by 10thfloor** [comment]
@MaxStalker Any word on this?

**Comment by MaxStalker** [comment]
@10thfloor we've identified a couple of solutions to said problem here:
https://github.com/onflow/flow-js-testing/issues/61

I have started with custom runner path, but no executable result atm. Still WIP 🙏

**Comment by MaxStalker** [comment]
@10thfloor can you check #150 for errors with Cypress tests?
They block check for that PR 😓

**Comment by 10thfloor** [comment]
Closing because stale. Tests have been added.
