### ISSUE TITLE
Create instructions for how to develop locally

### ISSUE THREAD

**Issue by srinjoyc** [onflow/kitty-items#75]
@srinjoyc commented on [Wed May 05 2021](https://github.com/onflow/flow/issues/496)

## Instructions

Currently there are no instructions on how to develop locally on kitty-items. Since most devs will at some point need to run locally, we should provide easy setup instructions to start. Eventually, we should automate and couple parts together to make it more seamless and integrated into the CLI.

### Issue To Be Solved
The following questions should be answered in the local instructions:
1. What other processes need to be running? IE. Emulator, Dev Wallet. How do these processes work, what do they do, and where can you learn more?
2. What configs need to change to run locally?

###  Solution
Directly add the instructions on the main README in a section called 'Running Locally'. 
  
### Notes
The dev wallet repo will need some updates and fixes to its documentation prior to doing this.

**Comment by MAkcanca** [comment]
One possible config to change is cadence/contracts/Kibble.cdc's Storage Paths. If one uses the same wallet account in the demo and tries to develop locally with the same account, `already stores an object` error will pop out.
```
self.VaultStoragePath = /storage/kibbleVault003
self.ReceiverPublicPath = /public/kibbleReceiver003
self.BalancePublicPath = /public/kibbleBalance003
self.AdminStoragePath = /storage/kibbleAdmin003
```

**Comment by comtechnet** [comment]
Please detail what you mean by "run locally" (also) - for example - right away I ran into the situation where the .env file did not exist - and the instructions imply that it "already exists" at the early stage of adding info to the .env file.

**Comment by cybercent** [comment]
@MAkcanca @srinjoyc 
Clean the path instead of changing to `003`
```
const CODE = cdc`
  import Kibble from 0xd07a7fa848ee5a9b
  import KittyItems from 0xd07a7fa848ee5a9b
  import KittyItemsMarket from 0xd07a7fa848ee5a9b
  transaction {
    prepare(acct: AuthAccount) {
      destroy(<- acct.load<@Kibble.Vault>(from: Kibble.VaultStoragePath)!)
      destroy(<- acct.load<@KittyItemsMarket.Collection>(from: KittyItemsMarket.CollectionStoragePath)!)
      destroy(<- acct.load<@KittyItems.Collection>(from: KittyItems.CollectionStoragePath)!)
    }
  }
 `
```

**Comment by aweijnitz** [comment]
Just commenting here to say that these instructions are sorely needed. The developer experience for a local setup is not where it needs to be for broader adoption.

**Comment by 10thfloor** [comment]
PR here: https://github.com/onflow/kitty-items/pull/95
