### ISSUE TITLE
.env file location - not specific enough - after clone of repo - no .env found - where is it?

### ISSUE THREAD

**Issue by comtechnet** [onflow/kitty-items#78]
Sorry - I little of a flow/kitty items newbie here - but in following the instructions - got stuck in VSCode - not knowing where the .env file was.  Do I need to create this file?  Please fix the doc so that the user knows specifically what to do here on this step.

I believe we are to take .env.example and create a .env from this example placing our values for flow_address and flow_private_key into the file and save .env back to the api folder where .env.example is located - is that correct?  If so - pls update the doc, if different- pls update the doc, instructions, etc.

**Comment by comtechnet** [comment]
doing a search on this repo - there is no .env file - so it is not supplied - so it must be generated by some step.

at a minimum - pls fix the doc and be specific about where this file "goes"

Save your keys
After your account has been created, save the address and private key in the .env file:

# Replace these values with your own!
FLOW_ADDRESS=0xabcdef12345689
FLOW_PRIVATE_KEY=aaaaaa...aaaaaa

**Comment by sideninja** [comment]
Solved in #82
