### ISSUE TITLE
Command Error: missing configuration, initialize it: flow init on "virgin" windows 10 system

### ISSUE THREAD

**Issue by comtechnet** [onflow/kitty-items#79]
On a clean Windows 10 "instance" / following the Kitty-Items install procedure / after successful steps 1 thru 3 - fails on step 4

4. Deploy the contracts
flow project deploy --network=testnet

Command Error: missing configuration, initialize it: flow init

Please resolve or change  the documentation so windows users can have a successful deployment or at least point them to where an addition step(s) should be for this to complete successfully

**Comment by sideninja** [comment]
Can you please confirm that you are using PowerShell? Was the` flow init` command actually ran and was it successful?
