### ISSUE TITLE
Fix Doc / Clarify readme to "export" or "set" environment variables for flow project deploy step

### ISSUE THREAD

**Issue by comtechnet** [onflow/kitty-items#81]
c:\Users\david\kitty-items>flow project deploy --network=testnet

Deploying 3 contracts for accounts: testnet-account

←[32;1mKibble←[0m -> 0xae7561b4bab9bc61
←[32;1mKittyItems←[0m -> 0xae7561b4bab9bc61
←[32;1mKittyItemsMarket←[0m -> 0xae7561b4bab9bc61

✨  All contracts deployed successfully

**Comment by comtechnet** [comment]
I don't think I can create a branch or another pull request - maybe this repo is locked down for that type of activity for new folks.

but here is m proposed change to the readme.md for this issue/change ...

### 4. Deploy the contracts

set or export your FLOW_ADDRESS and FLOW_PRIVATE_KEY variables/values

```sh
flow project deploy --network=testnet
```

**Comment by sideninja** [comment]
The same core of the problem as #78 and solved with PR #82
