### ISSUE TITLE
Clarify "minter" account - IS IT a new ACCOUNT or not?  or are we using an existing account we just created?

### ISSUE THREAD

**Issue by comtechnet** [onflow/kitty-items#84]
6. Set up the minter account
Before you can mint Kibbles and Kitty Items, you'll need to initialize your account with the following:

An empty Kibble vault
An empty KittyItems collection
An empty KittyItemsMarket collection
💡 Learn more about Vault and Collection resources in this tutorial.

Minter setup script
Run this script to set up the minter account and mint an initial supply of Kibble and Kitty Items:

**Comment by sideninja** [comment]
A Minter account is a new account you create and then set up.
> I would suggest you combine all the misunderstandings you have following the tutorial in a single issue so we can review it as a single ticket item and for questions you might have following the tutorial, I would encourage you to rather ask them on Discord.
