### ISSUE TITLE
Is metamask required for this step to work in the browser?  If so please update the doc.

### ISSUE THREAD

**Issue by comtechnet** [onflow/kitty-items#85]
Minter setup script
Run this script to set up the minter account and mint an initial supply of Kibble and Kitty Items:

./setup-minter.sh
Try it out!
✨ The API should now be available at http://localhost:3000.

**Comment by sideninja** [comment]
Metamask is never required. I would suggest you combine all the misunderstandings you have following the tutorial in a single issue so we can review it as a single ticket item and for questions you might have following the tutorial, I would encourage you to rather ask them on Discord.
