### ISSUE TITLE
Install does not work when hash algo is SHA2_256

### ISSUE THREAD

**Issue by cybercent** [onflow/kitty-items#86]
When using the `SHA2_256` hash algo on the faucet to create a Flow account, the config described in the readme does not work.

```
flow project deploy --network=testnet
```

```
❌  Kibble error: [Error Code: 1006] invalid proposal key: public key 0 on account e5c068f5a1155a3b does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account e5c068f5a1155a3b does not have a valid signature: signature is not valid
❌  KittyItems error: [Error Code: 1006] invalid proposal key: public key 0 on account e5c068f5a1155a3b does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account e5c068f5a1155a3b does not have a valid signature: signature is not valid
❌  KittyItemsMarket error: [Error Code: 1006] invalid proposal key: public key 0 on account e5c068f5a1155a3b does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account e5c068f5a1155a3b does not have a valid signature: signature is not valid

✨  All contracts deployed successfully
```

TODO:
- update readme to state that hash algo should be `SHA3_256`
- provide config to use `SHA2_256`

**Comment by sideninja** [comment]
Thank you for reporting this, we will make sure to update the docs.

CLI already supports SHA2_256 and you can configure it as it is described here: https://docs.onflow.org/flow-cli/configuration/#advanced-format-1

So if you want to have it configured you can do so but you must manually change `flow.json` configuration file.

**Comment by 10thfloor** [comment]
@sideninja So, is the default: `ECDSA_P256` + `SHA3_256` for keys, and anything else requires customization (using "advanced format") for keys entries in `flow.json` ?

Also, when using "advanced format" do you have to specify all properties, or can you omit defaults? For example, is this a valid "advanced format" entry: 

```
...

 {
    "hashAlgorithm": "SHA2_256",
    "context": {
          "privateKey": "333332967fd2bd75234ae9037dd4694c1f00baad63a10c35172bf65fbb8ad1111"
    }
},

...
```

**Comment by sideninja** [comment]
> @sideninja So, is the default: `ECDSA_P256` + `SHA3_256` for keys, and anything else requires customization (using "advanced format") for `keys` entries in `flow.json` ?
> 
> Also, when using "advanced format" do you have to specify all properties, or can you omit defaults?
> For example, is this a valid "advanced format" entry:
> 
> ```
> ...
> 
>  {
>     "hashAlgorithm": "SHA2_256",
>     "context": {
>           "privateKey": "333332967...etc"
>     }
> },
> 
> ...
> ```

Yes, that is the default.

You have to specify all the properties although specifying just the ones that are not the default might work although not tested for this usecase.

**Comment by KesleyDavid** [comment]
Good morning everybody.

For me I still have the same error when deploying to testnet.

```json
"testnet-account": {
      "address": "${FLOW_ADDRESS}",
      "keys": [
            {
                  "type": "hex",
                  "index": 0,
                  "signatureAlgorithm": "ECDSA_P256",
                  "hashAlgorithm": "SHA3_256",
                  "context": {
                        "privateKey": "${FLOW_PRIVATE_KEY}"
                   }
            }
      ]
}
```

**Comment by KesleyDavid** [comment]
@10thfloor,

After doing several tests and readings, I finally discovered the problem in my situation.

Currently `cli flow` is in version 0.21.0 and my installed version was different.

Make the test by updating your cli again:
https://docs.onflow.org/flow-cli/install

**Comment by sideninja** [comment]
@KesleyDavid new CLI version will warn you about the updates so you don't have a similar problem in the future. 

Can we close this?

**Comment by cybercent** [comment]
@sideninja yes, can be closed
