### ISSUE TITLE
 Invalid import FLOW_ADDRESS and FLOW_PRIVATE_KEY

### ISSUE THREAD

**Issue by chenxianqi** [onflow/kitty-items#87]
> tsnd --respawn src/index.ts

[INFO] 01:47:07 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)

No Flow account configured.

Did you export FLOW_ADDRESS and FLOW_PRIVATE_KEY?

**Comment by sideninja** [comment]
Can you please elaborate more? 
Did you actually export environment variables? 
What os/bash do you use?

**Comment by comtechnet** [comment]
The doc leaves MUCH to be desired.

It (the doc) "implies" you have to either export the variables (bash) or set the variables (powershell)

**Comment by 10thfloor** [comment]
Fixed in #82
