### ISSUE TITLE
TypeError: Cannot read property 'padStart' of null

### ISSUE THREAD

**Issue by hichana** [onflow/kitty-items#89]
Attempting [Step 6](https://github.com/onflow/kitty-items/tree/master/api#6-set-up-the-minter-account) of in the kitty-items api.

In the terminal, after executing the command `./setup-minter.sh`, this is displayed repeatedly (six times):
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;padStart&#39; of null<br> &nbsp; &nbsp;at /Users/mac-user/Documents/kitty-items/api/node_modules/@onflow/sdk/src/send/send-get-account.js:8:19<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:93:5)</pre>
</body>
</html>
```

In the terminal window connected to flow testnet, the error is:
```
TypeError: Cannot read property 'padStart' of null
    at /Users/mac-user/Documents/kitty-items/api/node_modules/@onflow/sdk/src/send/send-get-account.js:8:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
fromBlock=32442851 toBlock=32442853 latestBlock=32442853
```

If there are any more details that can help I'm happy to add in the comments -- thank you

**Comment by kulame** [comment]
i also got the same question.

TypeError: Cannot read property 'padStart' of null
    at /srv/blockchain/kitty-items/api/node_modules/@onflow/sdk/src/send/send-get-account.js:8:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read property 'padStart' of null
    at /srv/blockchain/kitty-items/api/node_modules/@onflow/sdk/src/send/send-get-account.js:8:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by srinjoyc** [comment]
What is the version of FCL/JS-SDK you are using?

**Comment by FlorianTopf** [comment]
I just ran into the same problem. I am doing the tutorial as @hichana. The same error message appears. 

I updated the FCL/JS-SDK to the latest version:
```
    "@onflow/fcl": "0.0.70",
    "@onflow/sdk": "0.0.46",
```

Still no luck.

**Comment by FlorianTopf** [comment]
**Update:**

I sipped through discord and found an intermediate solution to the issue: 

https://discord.com/channels/613813861610684416/699275726704083064/820019323271643186

I downgraded to fcl to version 0.0.66.
It seems that the function throwing the error in 0.0.70 was not changed, so something else must have change. I can dig deeper once I get a bit more familar with the system.

**Comment by valnermedeiros** [comment]
Having the same error:

`TypeError: Cannot read property 'padStart' of null`

Im using typescript and here are the package versions

```
    "@onflow/fcl": "^0.0.70",
    "@onflow/sdk": "^0.0.46",
    "@onflow/types": "^0.0.4",
    "@onflow/util-encode-key": "^0.0.2",
```

**Comment by srinjoyc** [comment]
Apologies everyone, there was a breaking change to FCL that went out in the spork a few days ago that needed to be updated on this repo - the fix was done by @10thfloor (https://github.com/onflow/kitty-items/pull/91) and should be all good now. Pull in the changes and please try again!
@valnermedeiros @FlorianTopf @kulame @hichana

**Comment by FlorianTopf** [comment]
I can confirm. This is working now. Might need to open another issue though.
