### ISSUE TITLE
Marketplace contract updates

### ISSUE THREAD

**Issue by psiemens** [onflow/kitty-items#9]
We've iterated on the design of the marketplace contract. We should update the Kitty Items example to reflect those changes.

**Comment by 10thfloor** [comment]
Stale.

**Comment by psiemens** [comment]
Reopening this -- we want to bring in the `NFTStorefront` contract from [this branch ](https://github.com/onflow/kitty-items/blob/rm/storefront/kitty-items-cadence/cadence/nftStorefront/contracts/NFTStorefront.cdc) into the main branch.
