### ISSUE TITLE
REQUEST: add Svelte front-end

### ISSUE THREAD

**Issue by lgs** [onflow/kitty-items#97]
Should be helpful having Svelte or Sveltekit front-end example other then React, new generation front-end devs won't use React anymore

**Comment by 10thfloor** [comment]
Great suggestion. We have rough versions in Vue, Svelte, and Alpine... We just need to polish them up for prime-time.
Do you think there is really a 'new generation' that is eschewing React in favour of these others?

**Comment by 10thfloor** [comment]
This should be possible now thanks to: 
https://github.com/bluesign/fcl-svelte-rollup
