### ISSUE TITLE
Add FUSD to Kitty Items

### ISSUE THREAD

**Issue by psiemens** [onflow/kitty-items#99]
**Is your feature request related to a problem? Please describe.**

Developers want to start using FUSD in their applications, but lack a concrete example demonstrating how to do so.

**Describe the solution you'd like**

Ideally Kitty Items can be updated with the following:

- Merge in generic storefront contract, which can support multiple fungible tokens out of the box (unlike `KittyItemsMarket`, which is hard-coded to `Kibble`) (issue: #9) 
- We would keep the `Kibble` contract and minting functionality in the API
- When building the frontend, developers can use a flag to build for `FUSD` or `Kibble`
- The built UI will change based on the token option selected
- FUSD is highlighted as the default, but developers can opt to run the `Kibble` version if they are interested in creating their own fungible token.

**Comment by psiemens** [comment]
You should use this version of the contract in Kitty Items: https://github.com/onflow/wallet-api/blob/main/cadence/contracts/FUSD.cdc

Here is an example of how to add FUSD to `flow.json`

**Comment by 10thfloor** [comment]
Closed by #127
